config/routes.rb
LocaPeople::Application.routes.draw do

  resources :events

  resources :performers

  resources :users

  resources :venues

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  root :to => 'pages#landingPage'

end

app/views/pages/landingPage.html.erb
<%= javascript_include_tag "controllers/pagesController" %>

<canvas id='landing-canvas'>
</canvas> 

<img class="logo" src="assets/logo1.png">

<div class="content">
	<ul id="sdt_menu" class="sdt_menu">
		<li>
			<a href="#">
				<img src="assets/image02.jpg" alt=""/>
				<span class="sdt_active"></span>
				<span class="sdt_wrap">
					<span class="sdt_link">Search</span>
					<span class="sdt_descr">Launch the PartyBot</span>
				</span>
			</a>
				<div class="sdt_box">
				  <%= link_to 'Party Map', venues_path %>
				</div>
		</li>
		<li>
			<a href="#">
				<img src="assets/image03.jpg" alt=""/>
				<span class="sdt_active"></span>
				<span class="sdt_wrap">
					<span class="sdt_link">Global PartyBot</span>
					<span class="sdt_descr">Hot Events</span>
				</span>
			</a>
		</li>
		<li>
			<a href="#">
				<img src="assets/image04.jpg" alt=""/>
				<span class="sdt_active"></span>
				<span class="sdt_wrap">
				<% if user_signed_in? %>
					<span class="sdt_link">Your Bot</span>
					<span class="sdt_descr">Profile</span>
				<% else %>
					<span class="sdt_link">Activate your Bot</span>
					<span class="sdt_descr">Login/Signup</span>
				<% end %>
				</span>
			</a>
			<% if user_signed_in? %>
				<div class="sdt_box">
					<%= link_to "Your Profile", user_path(current_user) %>
					<%= link_to 'Logout', signout_path %>
				</div>
			<% else %>
				<div class="sdt_box">
					<%= link_to "Facebook", "/auth/facebook", class:'sign_in' %>
					<%= link_to "Google", "/auth/google_login", class:'sign_in' %>
				</div>
			<% end %>
		</li>
		<li>
			<a href="#">
				<img src="assets/image12.jpg" alt=""/>
				<span class="sdt_active"></span>
				<span class="sdt_wrap">
					<span class="sdt_link">About the Bot</span>
					<span class="sdt_descr">Meet the PartyBot</span>
				</span>
			</a>
		</li>
	</ul>
</div>