config/routes.rb
LocaPeople::Application.routes.draw do

  resources :events

  resources :performers

  resources :users

  resources :venues

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  root :to => 'pages#landingPage'

end

app/models/performer.rb
class Performer < ActiveRecord::Base
	# attr_accessible :id, :name, :description, :user_id, :hometown_city_id
	
	has_many 		:performer_tribes
	has_many 		:lookup_tribe_types, 	:through => :performer_tribes

	has_many 		:performer_musics
	has_many 		:lookup_music_types, 	:through => :performer_musics

	has_many 		:performer_languages
	has_many 		:lookup_languages, 		:through => :performer_languages

  has_many 		:performer_ratings
	has_many 		:lookup_rating_types, :through => :performer_ratings
  
  belongs_to 	:user
  belongs_to  :hometown_city, 			:class_name => "LookupCity"

  # attr_accessible :title, :body
end

app/controllers/performers_controller.rb
class PerformersController < ApplicationController
  # GET /performers
  # GET /performers.json
  def index
    @performers = Performer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @performers }
    end
  end

  # GET /performers/1
  # GET /performers/1.json
  def show
    @performer = Performer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @performer }
    end
  end

  # GET /performers/new
  # GET /performers/new.json
  def new
    @performer = Performer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @performer }
    end
  end

  # GET /performers/1/edit
  def edit
    @performer = Performer.find(params[:id])
  end

  # POST /performers
  # POST /performers.json
  def create
    @performer = Performer.new(params[:performer])

    respond_to do |format|
      if @performer.save
        format.html { redirect_to @performer, notice: 'Performer was successfully created.' }
        format.json { render json: @performer, status: :created, location: @performer }
      else
        format.html { render action: "new" }
        format.json { render json: @performer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /performers/1
  # PUT /performers/1.json
  def update
    @performer = Performer.find(params[:id])

    respond_to do |format|
      if @performer.update_attributes(params[:performer])
        format.html { redirect_to @performer, notice: 'Performer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @performer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /performers/1
  # DELETE /performers/1.json
  def destroy
    @performer = Performer.find(params[:id])
    @performer.destroy

    respond_to do |format|
      format.html { redirect_to performers_url }
      format.json { head :no_content }
    end
  end

  private

    def performer_params
      params.require(:performer).permit(:id, :name, :description, :user_id, :hometown_city_id)
    end

end

app/helpers/performers_helper.rb
module PerformersHelper
end

app/views/performers/_form.html.erb
<%= form_for(@performer) do |f| %>
  <% if @performer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@performer.errors.count, "error") %> prohibited this performer from being saved:</h2>

      <ul>
      <% @performer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/performers/edit.html.erb
<h1>Editing performer</h1>

<%= render 'form' %>

<%= link_to 'Show', @performer %> |
<%= link_to 'Back', performers_path %>

app/views/performers/index.html.erb
<h1>Listing performers</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @performers.each do |performer| %>
  <tr>
    <td><%= link_to 'Show', performer %></td>
    <td><%= link_to 'Edit', edit_performer_path(performer) %></td>
    <td><%= link_to 'Destroy', performer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Performer', new_performer_path %>

app/views/performers/new.html.erb
<h1>New performer</h1>

<%= render 'form' %>

<%= link_to 'Back', performers_path %>

app/views/performers/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_performer_path(@performer) %> |
<%= link_to 'Back', performers_path %>